### ISSUE TITLE
Why OLEAutomation(False)?

### ISSUE THREAD

**Issue by Greedquest** [fafalone/tbShellLib#10]
Is this restriction necessary? For example, if I want to return an ITypeInfo from a function in a dll I call from VBA, will I be able to with this flag?

**Comment by fafalone** [comment]
The flag was a temporary workaround so RegisterTypeLib wouldn't register 3rd party interfaces (i.e. all of them in tbShellLib), as that call would fail, causing ActiveX control builds to fail.

It's no longer neccessary since tB now has a custom replacement for that function controlled by the `[ ComImport ]` attribute, but the default value is not registering so that didn't need to be added.

So `[ OleAutomation(False) ]` tags can be removed, but the vast majority of interfaces should not be marked with this attribute. Specifically, ITypeInfo should not have this attribute as it does not have it in the SDK headers. This attribute would only be found on things like the shell automation objects like IWebBrowser, but it shouldn't be necessary to use them.

**Comment by Greedquest** [comment]
Thanks, I didn't realise there was an SDK standard you were working to and that of course makes sense. For some reason it's still showing up in my ActiveX Dll and I can make an `ITypeLib` variable in VBA no issue, so maybe I'm misunderstanding what it does anyway.
